In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_excel('3 columns.xls')
data

    area  bedrooms    price
0   3050         3  3920000
1   3100         2  2135000
2   4320         3  4690000
3   3060         3  3465000
4   2575         2  3290000
..   ...       ...      ...
95  6600         4  9100000
96  2145         3  4200000
97  5200         4  2852500
98  4410         2  4200000
99  8400         3  5250000

[100 rows x 3 columns]

In [4]:
# We need to find the best fitting plane z = a1x + a2y + a3
# We can use the least squares method to find the best fitting plane

In [5]:
B = data.values
B

array([[    3050,        3,  3920000],
       [    3100,        2,  2135000],
       [    4320,        3,  4690000],
       [    3060,        3,  3465000],
       [    2575,        2,  3290000],
       [    8960,        4, 12250000],
       [    6600,        3,  6090000],
       [    3800,        2,  3045000],
       [    4992,        3,  4060000],
       [    2400,        3,  1767150],
       [    3512,        2,  3500000],
       [    4500,        3,  3990000],
       [    5400,        3,  4025000],
       [    3180,        2,  2310000],
       [    4040,        2,  4095000],
       [    3180,        4,  3290000],
       [    2817,        4,  5495000],
       [    6615,        3,  2940000],
       [    6540,        3,  5950000],
       [    3520,        2,  4515000],
       [    4500,        2,  3080000],
       [    5700,        3,  6650000],
       [    4840,        2,  2450000],
       [    7250,        3,  4200000],
       [    3090,        3,  3010000],
       [    3745,        3,  4655000],
       [    3090,        2,  3080000],
       [    9185,        4,  7245000],
       [    8250,        3,  6510000],
       [    6255,        3,  5775000],
       [    5200,        3,  5810000],
       [    4410,        4,  4970000],
       [    6600,        4,  5600000],
       [   12900,        3,  4900000],
       [    4340,        3,  4060000],
       [    5750,        3,  9800000],
       [    4775,        4,  3325000],
       [    6000,        4,  7700000],
       [    2910,        3,  1750000],
       [    3090,        2,  2450000],
       [    7000,        3,  4795000],
       [    2145,        3,  3465000],
       [    3240,        2,  2450000],
       [    5400,        4,  2870000],
       [    6725,        3,  7580000],
       [    5960,        3,  8190000],
       [    3300,        3,  5530000],
       [    3500,        4,  4340000],
       [    4079,        3,  4200000],
       [    4600,        3,  8890000],
       [    4000,        3,  6790000],
       [    7482,        3,  8043000],
       [    2000,        2,  2660000],
       [    3150,        3,  2940000],
       [    2135,        3,  3500000],
       [    4120,        2,  4900000],
       [    3850,        3,  3115000],
       [    2145,        4,  3920000],
       [    4500,        3,  4007500],
       [    4080,        2,  3850000],
       [    6100,        3,  5110000],
       [    4080,        3,  4165000],
       [    6710,        3,  5390000],
       [    5010,        3,  4620000],
       [    3986,        2,  3150000],
       [    7320,        4,  5950000],
       [    8800,        3,  8575000],
       [    3480,        3,  2940000],
       [   10240,        2,  4760000],
       [    6360,        4,  7035000],
       [    3480,        2,  3745000],
       [    4880,        4,  8295000],
       [    3990,        3,  3500000],
       [    8250,        3,  3773000],
       [    8400,        4,  4550000],
       [    6235,        3,  7350000],
       [    4160,        3,  4830000],
       [    5885,        2,  4480000],
       [    5320,        3,  4550000],
       [    9800,        4,  5250000],
       [    3460,        3,  4025000],
       [    6100,        3,  5530000],
       [    4350,        3,  2835000],
       [    3880,        3,  4620000],
       [    5495,        3,  3129000],
       [    3650,        3,  3500000],
       [    6540,        4,  8540000],
       [    6360,        2,  4270000],
       [    3450,        1,  3150000],
       [    9000,        3,  6300000],
       [   11460,        3,  5873000],
       [    3792,        4,  3290000],
       [    3640,        3,  4200000],
       [    3450,        3,  3150000],
       [    3450,        2,  1820000],
       [    6600,        4,  9100000],
       [    2145,        3,  4200000],
       [    5200,        4,  2852500],
       [    4410,        2,  4200000],
       [    8400,        3,  5250000]], dtype=int64)

In [6]:
x = B[:,0]
y = B[:,1]
z = B[:,2]

In [7]:
A = np.vstack([x, y, np.ones(len(x))]).T
A

array([[3.050e+03, 3.000e+00, 1.000e+00],
       [3.100e+03, 2.000e+00, 1.000e+00],
       [4.320e+03, 3.000e+00, 1.000e+00],
       [3.060e+03, 3.000e+00, 1.000e+00],
       [2.575e+03, 2.000e+00, 1.000e+00],
       [8.960e+03, 4.000e+00, 1.000e+00],
       [6.600e+03, 3.000e+00, 1.000e+00],
       [3.800e+03, 2.000e+00, 1.000e+00],
       [4.992e+03, 3.000e+00, 1.000e+00],
       [2.400e+03, 3.000e+00, 1.000e+00],
       [3.512e+03, 2.000e+00, 1.000e+00],
       [4.500e+03, 3.000e+00, 1.000e+00],
       [5.400e+03, 3.000e+00, 1.000e+00],
       [3.180e+03, 2.000e+00, 1.000e+00],
       [4.040e+03, 2.000e+00, 1.000e+00],
       [3.180e+03, 4.000e+00, 1.000e+00],
       [2.817e+03, 4.000e+00, 1.000e+00],
       [6.615e+03, 3.000e+00, 1.000e+00],
       [6.540e+03, 3.000e+00, 1.000e+00],
       [3.520e+03, 2.000e+00, 1.000e+00],
       [4.500e+03, 2.000e+00, 1.000e+00],
       [5.700e+03, 3.000e+00, 1.000e+00],
       [4.840e+03, 2.000e+00, 1.000e+00],
       [7.250e+03, 3.000e+00, 1.000e+00],
       [3.090e+03, 3.000e+00, 1.000e+00],
       [3.745e+03, 3.000e+00, 1.000e+00],
       [3.090e+03, 2.000e+00, 1.000e+00],
       [9.185e+03, 4.000e+00, 1.000e+00],
       [8.250e+03, 3.000e+00, 1.000e+00],
       [6.255e+03, 3.000e+00, 1.000e+00],
       [5.200e+03, 3.000e+00, 1.000e+00],
       [4.410e+03, 4.000e+00, 1.000e+00],
       [6.600e+03, 4.000e+00, 1.000e+00],
       [1.290e+04, 3.000e+00, 1.000e+00],
       [4.340e+03, 3.000e+00, 1.000e+00],
       [5.750e+03, 3.000e+00, 1.000e+00],
       [4.775e+03, 4.000e+00, 1.000e+00],
       [6.000e+03, 4.000e+00, 1.000e+00],
       [2.910e+03, 3.000e+00, 1.000e+00],
       [3.090e+03, 2.000e+00, 1.000e+00],
       [7.000e+03, 3.000e+00, 1.000e+00],
       [2.145e+03, 3.000e+00, 1.000e+00],
       [3.240e+03, 2.000e+00, 1.000e+00],
       [5.400e+03, 4.000e+00, 1.000e+00],
       [6.725e+03, 3.000e+00, 1.000e+00],
       [5.960e+03, 3.000e+00, 1.000e+00],
       [3.300e+03, 3.000e+00, 1.000e+00],
       [3.500e+03, 4.000e+00, 1.000e+00],
       [4.079e+03, 3.000e+00, 1.000e+00],
       [4.600e+03, 3.000e+00, 1.000e+00],
       [4.000e+03, 3.000e+00, 1.000e+00],
       [7.482e+03, 3.000e+00, 1.000e+00],
       [2.000e+03, 2.000e+00, 1.000e+00],
       [3.150e+03, 3.000e+00, 1.000e+00],
       [2.135e+03, 3.000e+00, 1.000e+00],
       [4.120e+03, 2.000e+00, 1.000e+00],
       [3.850e+03, 3.000e+00, 1.000e+00],
       [2.145e+03, 4.000e+00, 1.000e+00],
       [4.500e+03, 3.000e+00, 1.000e+00],
       [4.080e+03, 2.000e+00, 1.000e+00],
       [6.100e+03, 3.000e+00, 1.000e+00],
       [4.080e+03, 3.000e+00, 1.000e+00],
       [6.710e+03, 3.000e+00, 1.000e+00],
       [5.010e+03, 3.000e+00, 1.000e+00],
       [3.986e+03, 2.000e+00, 1.000e+00],
       [7.320e+03, 4.000e+00, 1.000e+00],
       [8.800e+03, 3.000e+00, 1.000e+00],
       [3.480e+03, 3.000e+00, 1.000e+00],
       [1.024e+04, 2.000e+00, 1.000e+00],
       [6.360e+03, 4.000e+00, 1.000e+00],
       [3.480e+03, 2.000e+00, 1.000e+00],
       [4.880e+03, 4.000e+00, 1.000e+00],
       [3.990e+03, 3.000e+00, 1.000e+00],
       [8.250e+03, 3.000e+00, 1.000e+00],
       [8.400e+03, 4.000e+00, 1.000e+00],
       [6.235e+03, 3.000e+00, 1.000e+00],
       [4.160e+03, 3.000e+00, 1.000e+00],
       [5.885e+03, 2.000e+00, 1.000e+00],
       [5.320e+03, 3.000e+00, 1.000e+00],
       [9.800e+03, 4.000e+00, 1.000e+00],
       [3.460e+03, 3.000e+00, 1.000e+00],
       [6.100e+03, 3.000e+00, 1.000e+00],
       [4.350e+03, 3.000e+00, 1.000e+00],
       [3.880e+03, 3.000e+00, 1.000e+00],
       [5.495e+03, 3.000e+00, 1.000e+00],
       [3.650e+03, 3.000e+00, 1.000e+00],
       [6.540e+03, 4.000e+00, 1.000e+00],
       [6.360e+03, 2.000e+00, 1.000e+00],
       [3.450e+03, 1.000e+00, 1.000e+00],
       [9.000e+03, 3.000e+00, 1.000e+00],
       [1.146e+04, 3.000e+00, 1.000e+00],
       [3.792e+03, 4.000e+00, 1.000e+00],
       [3.640e+03, 3.000e+00, 1.000e+00],
       [3.450e+03, 3.000e+00, 1.000e+00],
       [3.450e+03, 2.000e+00, 1.000e+00],
       [6.600e+03, 4.000e+00, 1.000e+00],
       [2.145e+03, 3.000e+00, 1.000e+00],
       [5.200e+03, 4.000e+00, 1.000e+00],
       [4.410e+03, 2.000e+00, 1.000e+00],
       [8.400e+03, 3.000e+00, 1.000e+00]])

In [9]:
beta = np.dot(np.linalg.inv(np.dot(A.T,A)),np.dot(A.T,z.T))
print(beta)

[4.11335474e+02 8.32351204e+05 1.40790447e+05]